# 实验配置文件（精简版）
# 仅包含非物理约束模型：MLP、KAN-Poly、KAN-Bspline

# 全局设置
global_settings:
  # 数据路径
  nsfnet_test_dir: "data/routenet/nsfnetbw/tfrecords/evaluate"
  gbn_test_dir: "data/routenet/gbnbw/tfrecords/evaluate"

  # 模型目录基础路径（与 train_models.py 保持一致）
  models_base_dir: "fixed_model/0925"

  # 实验参数
  batch_size: 32

  # ================= 新增：评估与数值实验的独立控制 =================
  # 对 evaluate_routenet_tf2.py 执行完整测试集评估：
  # true -> 不传递 --num_samples，脚本内部遍历全部样本
  # false -> 使用下面的 num_samples_evaluate（若未设置则回退到 num_samples）
  evaluate_full: true

  # （可选）只在 evaluate_full: false 时生效；如果想指定评估采样数量可填写，例如 1500
  # num_samples_evaluate: 1500

  # numerical 分析使用的采样数量（必要；覆盖通用 num_samples）
  num_samples_numerical: 2000

  # （回退值）如果上面两个专用键缺失，会使用此通用值；保留兼容性
  num_samples: 2000

  # 输出根目录
  base_output_dir: "experiment_results/0925"

# 模型配置方案（由运行器自动生成 models）
model_configs:
  - type: "mlp"
    physics: "none"
    enabled: true

  - type: "kan"
    physics: "none"
    enabled: true  # KAN-Poly

  - type: "kan_bspline"
    physics: "none"
    enabled: true  # KAN-Bspline
    kan_basis: "bspline"
    kan_grid_size: 5
    kan_spline_order: 3

# 实验定义
experiments:
  evaluate:
    script: "routenet/evaluate_routenet_tf2.py"
    required_args:
      - "delay_model_dir"
      - "nsfnet_test_dir"
      - "gbn_test_dir"
      - "output_dir"
    optional_args:
      - "batch_size"
      - "num_samples"
      - "kan"
      # 可选：如果需要强制 TF 2.9 兼容评估脚本
      # - "tf-compat"

  numerical:
    script: "routenet/numerical_analysis.py"
    required_args:
      - "model_dir"
      - "nsfnet_test_dir"
      - "gbn_test_dir"
      - "output_dir"
    optional_args:
      - "batch_size"
      - "num_samples"
      - "kan"
